### ISSUE TITLE
Proxy Script

### ISSUE THREAD

**Issue by bonxz** [jackuoll/new-world-chest-tracker#1]
> Optionally there is a script to proxy the NW Minimap websocket if you wish to run this on a PC different to the one you are playing on.

Can you explain how to get this to work?

Or would it be an option that you can include other NewWorld map as well? https://www.overwolf.com/app/Leon_Machens-Aeternum_Map

**Comment by jackuoll** [comment]
For the proxy script, you want to be running it on the machine that is playing New World. I run this as a service using NSSM (because NSSM will handle restarting the script if it fails - not sure if it ever does fail).

You need to set the NW Server Proxy URL in your settings using a .env file. Eg:

```
ws_proxy_server_url=192.168.0.10
ws_proxy_server_port=8765
```

Then on the web server side, you need to also specify the IP of the proxy server you're connecting to with the `nw_wss_server_location` variable.

If you just want to run it on your local PC and not worry about running the web server on a different PC, you don't need to run the proxy at all, just `main.py` (to populate data) and `uvicorn web:app --reload` to have the web server available.

For now at least, there is only support for New World Mini Map. This project is more or less for my personal usage at the moment and I just decided to leave it open source in case anyone is interested in using it. If you want to make a PR to support other minimap websockets, feel free.
